name: pnpm cache

on:
  workflow_dispatch:
  schedule:
    # Run every day at 01:00 UTC
    - cron: '0 1 * * *'

jobs:
  create-cache:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'DefinitelyTyped/DefinitelyTyped' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Get pnpm cache info
        id: pnpm-cache
        run: |
          echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT
          echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: pnpm install
        run: pnpm install

      - name: Save pnpm cache
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ steps.pnpm-cache.outputs.store }}
          key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
