name: pnpm cache

on:
  workflow_dispatch:
  schedule:
    # Run every day at 01:00 UTC
    - cron: '0 1 * * *'

jobs:
  create-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Get pnpm cache info
        id: pnpm-cache
        run: |
          echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT
          echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: pnpm install
        run: pnpm install

      - name: Save pnpm cache
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ${{ steps.pnpm-cache.outputs.store }}
          key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
