name: pnpm cache

on:
  workflow_dispatch:
  schedule:
    # Run every day at 01:00 UTC
    - cron: '0 1 * * *'

jobs:
  create-cache:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'DefinitelyTyped/DefinitelyTyped' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Get pnpm cache info
        id: pnpm-cache
        run: |
          echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT
          echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: pnpm install
        run: pnpm install

      - name: Save pnpm cache
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ${{ steps.pnpm-cache.outputs.store }}
          key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
