name: Search commit
run-name: ${{ github.actor }} is searching for a commit ğŸš€
on: [workflow_dispatch]
jobs:
  Search-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Search-commit job running
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"; 
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Find the commits
        run: |
          git rev-list --graph --objects --in-commit-order --filter=blob:none HEAD -- types | grep -C10 b58b7b964940dc77756
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      
