name: Search commit
run-name: Searching for a commit... [${{ github.actor }}] ğŸš€
on: [workflow_dispatch]
jobs:
  Search-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Search-commit job running
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"; 
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        run: true
      - name: Find the commits
        run: |
          x=$(git rev-list --objects --in-commit-order --filter=blob:none HEAD -- types | grep -C2 b58b7b964940dc77756);
          y=$(for i in $x; do echo $i; break; done)
      - name: "Result: $y"
        run: echo "$x";
      - name: "ğŸ Job status: ${{ job.status }}."
        run: true
      
