name: Test workflows
run-name: Trying to understand what happens ğŸš€
on: [workflow_dispatch]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test job running
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"; 
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Tests, part 1 $x
        run: |
          export x="This is set as x"
          export y="This is now y"
      - name: "Result: $y"
        run: echo "$x";
      - name: "ğŸ Job status: ${{ job.status }}."
        run: echo ${{ runner.toJSON }}
        
