name: typescript-bot watchdog

on:
  schedule:
    # Hourly
    - cron: '42 * * * *'
  workflow_dispatch:

jobs:
  watchdog:
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/setup-for-scripts

      - run: node ./scripts/watchdog-typescript-bot.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
