name: Publisher watchdog

on:
  schedule:
    # Hourly
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  watchdog:
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/setup-for-scripts

      - run: node ./scripts/watchdog-publisher.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify dedicated teams channel
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@28e5ca976c053d54e2b852f3f38da312f35a24fc # v1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WATCHDOG_WEBHOOK_URI }}
          notification-summary: Publisher watchdog failed
          notification-color: dc3545
          timezone: America/Los_Angeles
          verbose-logging: true
